name: Build and release the app

on:
  workflow_dispatch:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Get version'
        run: echo "version=$(git describe --tag)" >> $GITHUB_ENV

      - name: 'Build static application'
        run: |
          make re AIO=true && \
          tar -czvf "select-static-${{env.version}}-x86_64.tar.gz" select

      - name: 'Build application'
        run: |
          make re && \
          tar -czvf select-${{env.version}}-x86_64.tar.gz select

      - name: 'Create release'
        uses: 'akkuman/gitea-release-action@v1'
        env:
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
        with:
          tag_name: ${{env.version}}
          name: Release - ${{env.version}}
          draft: true
          prerelease: true
          files: |
            select-${{env.version}}-x86_64.tar.gz
            select-static-${{env.version}}-x86_64.tar.gz
